version: '3'
services: 
    node-auth-token:
        build: .
        image: node-auth-token
        container_name: node-auth-token
        ports: 
            - "3000:5000"
        volumes: 
            - ".:/usr/src/app"
        command: node server.js
        network_mode: bridge